### ISSUE TITLE
Whether leap 3.1 is supported now？

### ISSUE THREAD

**Issue by leezijie** [eosrio/hyperion-history-api#124]
I used the version of Leap3.1 to start the node, but the snapshot uses version V6. But when I start./run EOS-Indexer, I cannot import block data.

logs: No blocks processed! Indexer will stop in 25 seconds!

**Comment by jun0tpyrc** [comment]
even on v3.3.6 
```
2022-09-05T01:47:02: | SHIP Status Report
2022-09-05T01:47:02: | Init block: 33254515
2022-09-05T01:47:02: | Head block: 33267345
2022-09-05T01:47:03: Error: type "get_blocks_request_v1" is not valid for variant
2022-09-05T01:47:03:     at Object.serializeVariant [as serialize] (/hyperion-history-api/addons/src/eosjs-serialize.ts:674:15)
2022-09-05T01:47:03:     at Object.serialize (/hyperion-history-api/helpers/common_functions.ts:151:33)
2022-09-05T01:47:03:     at StateReader.send (/hyperion-history-api/workers/state-reader.ts:499:18)
2022-09-05T01:47:03:     at StateReader.requestBlocks (/hyperion-history-api/workers/state-reader.ts:495:8)
2022-09-05T01:47:03:     at StateReader.onMessage (/hyperion-history-api/workers/state-reader.ts:342:13)
2022-09-05T01:47:03:     at StateReader.processIncomingBlocks (/hyperion-history-api/workers/state-reader.ts:278:17)
2022-09-05T01:47:03:     at /hyperion-history-api/workers/state-reader.ts:54:9
```


please suggest , 

tried 
```
parser": "2.1"/"1.8"
```
not working

**Comment by jun0tpyrc** [comment]
@igorls  🙏 
seeing release v3.3.6 mentioning something about Leap/NodeosRPC
Are there being specific config for keeping compatible with leap  /& could that be an example /& is hyperion fully ready ?

**Comment by jun0tpyrc** [comment]
it looks supported, these two must pair up
```
   "parser": "1.8",
    "ship_request_rev": ""
```

**Comment by hotcoin-walle** [comment]
> 

how to setting it? 

which file?

**Comment by jun0tpyrc** [comment]
> > it looks supported, these two must pair up
> > ```
> >    "parser": "1.8",
> >    "ship_request_rev": ""
> > ```
> 
> how to setting it?
> 
> which file?

in the chain's own config.json
