### ISSUE TITLE
Cannot find module './socketManager'

### ISSUE THREAD

**Issue by github10000** [eosrio/Hyperion-History-API#23]
I get master code，found an error on deploy，how is fixed? as follows.

- /opt/Hyperion-History-API/api/api-loader.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:794:15)
    at Module.Hook._require.Module.require (/usr/lib/node_modules/pm2/node_modules/require-in-the-middle/index.js:51:29)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/opt/Hyperion-History-API/api/api-loader.js:20:29)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at /usr/lib/node_modules/pm2/lib/ProcessContainer.js:297:23
    at wrapper (/usr/lib/node_modules/pm2/node_modules/async/internal/once.js:12:16)
    at next (/usr/lib/node_modules/pm2/node_modules/async/waterfall.js:96:20)
    at /usr/lib/node_modules/pm2/node_modules/async/internal/onlyOnce.js:12:16
    at WriteStream.<anonymous> (/usr/lib/node_modules/pm2/lib/Utility.js:186:13)
    at WriteStream.emit (events.js:210:5)
    at internal/fs/streams.js:299:10
    at FSReqCallback.oncomplete (fs.js:146:23)
Error: Cannot find module './socketManager'

**Comment by bakasura980** [comment]
In ecosystem.config.js set ENABLE_WEBSOCKET and ENABLE_SOCKETIO to false in order to run it
