### ISSUE TITLE
Hyperion fails when action receipt is null on 1.8 nodeos

### ISSUE THREAD

**Issue by fschoell** [eosrio/Hyperion-History-API#8]
Just ran the Hyperion 1.8 pre-release on the kylin testnet. I'm getting actions with `null` receipts which make hyperion fail:

```
0|Indexer  | TypeError: Cannot read property '1' of null
0|Indexer  |     at processAction (/home/pm2/hyperion/workers/deserializer.worker.js:333:46)
0|Indexer  |     at processTicksAndRejections (internal/process/task_queues.js:86:5)
0|Indexer  | { action_ordinal: 1,
0|Indexer  |   creator_action_ordinal: 0,
0|Indexer  |   receipt: null,
0|Indexer  |   receiver: 'eosio.token',
0|Indexer  |   act:
0|Indexer  |    { account: 'eosio.token',
0|Indexer  |      name: 'transfer',
0|Indexer  |      authorization: [ [Object] ],
0|Indexer  |      data: { memo: '75,,' } },
0|Indexer  |   context_free: false,
0|Indexer  |   elapsed: '0',
0|Indexer  |   except: 'Y',
0|Indexer  |   error_code: '10000000000000000000',
0|Indexer  |   '@transfer':
0|Indexer  |    { from: 'blackjackeee',
0|Indexer  |      to: 'godappdice12',
0|Indexer  |      amount: 0.5,
0|Indexer  |      symbol: 'EOS' },
0|Indexer  |   '@timestamp': '2019-03-11T21:36:43.000',
0|Indexer  |   block_num: 38118232,
0|Indexer  |   producer: 'superoneiobp',
0|Indexer  |   trx_id:
0|Indexer  |    '4133195894f3116fcc7ace75edb3b17cdd7926045851e2930836d0c1e2b6a723' }
```

Not sure whether this can only appear on testnets like kylin. However, it seems like there's no way to skip those actions, Hyperion is just going to spam the logs and won't keep on processing the next blocks.

**Comment by igorls** [comment]
this was fixed on the latest commit, let me know if you run into problems again, please notice the new tags on the example ecosystem file before updating
