### ISSUE TITLE
Fix_missing_blocks script error

### ISSUE THREAD

**Issue by bensig** [eosrio/hyperion-history-api#95]
This fails with "UnicodeEncodeError: 'latin-1' codec can't encode characters in position 43-44: ordinal not in range(256)" 

 ```
====================================================================================================
Searching for missing Blocks  
scripts/fix_missing_blocks/fix-missing-blocks.py:131: DeprecationWarning: The 'body' parameter is deprecated for the 'search' API and will be removed in a future version. Instead use API parameters directly. See https://github.com/elastic/elasticsearch-py/issues/1698 for more information
  result = es.search(index="proton-block-*", body=query)
scripts/fix_missing_blocks/fix-missing-blocks.py:247: DeprecationWarning: The 'body' parameter is deprecated for the 'search' API and will be removed in a future version. Instead use API parameters directly. See https://github.com/elastic/elasticsearch-py/issues/1698 for more information
  result = es.search(index="proton-block-*", body=query_body2(gte,lte,1000))
 ====================================================================================================
Completed Search  
 ====================================================================================================
1.Building replacement text for config file  
 ====================================================================================================
2.Updating the config file  
 ====================================================================================================
3.Config file is now updated for:  0 - 1000 
 ====================================================================================================
4.Running Re-indexing for:  0 - 1000 

2022-04-02T16:45:30: [2051214 - 00_master] Last indexed block (deltas): 121070391

2022-04-02T16:45:30: [2051214 - 00_master]  |>> First Block: 0

2022-04-02T16:45:30: [2051214 - 00_master]  >>| Last  Block: 1000

2022-04-02T16:45:30: [2051214 - 00_master] Setting parallel reader [1] from block 0 to 1000

2022-04-02T16:45:30: [2051214 - 00_master] Loading indices...

2022-04-02T16:45:31: [2051214 - 00_master] ActionIndex: proton-action-v1-000002 | First: 10000001 | Last: 20000000

2022-04-02T16:45:32: [2051214 - 00_master] ActionIndex: proton-action-v1-000003 | First: 20000001 | Last: 30000000

2022-04-02T16:45:32: [2051214 - 00_master] ActionIndex: proton-action-v1-000004 | First: 30000001 | Last: 40000000

2022-04-02T16:45:38: [2051214 - 00_master] ActionIndex: proton-action-v1-000005 | First: 40000001 | Last: 50000000

2022-04-02T16:45:39: [2051214 - 00_master] ActionIndex: proton-action-v1-000001 | First: 2 | Last: 10000000

2022-04-02T16:45:45: [2051214 - 00_master] ActionIndex: proton-action-v1-000006 | First: 50000001 | Last: 60000000

2022-04-02T16:45:51: [2051214 - 00_master] ActionIndex: proton-action-v1-000007 | First: 60000001 | Last: 70000000

2022-04-02T16:45:51: [2051214 - 00_master] ActionIndex: proton-action-v1-000008 | First: 70000001 | Last: 80000000

2022-04-02T16:45:51: [2051214 - 00_master] ActionIndex: proton-action-v1-000009 | First: 80000001 | Last: 80635816

2022-04-02T16:45:52: [2051214 - 00_master] ActionIndex: proton-action-v1-000013 | First: 120000001 | Last: 121070391

2022-04-02T16:45:52: [2051214 - 00_master] ActionIndex: proton-action-v1-000010 | First: 100000000 | Last: 100000000

2022-04-02T16:45:52: [2051214 - 00_master] ActionIndex: proton-action-v1-000011 | First: 100000001 | Last: 100005113

2022-04-02T16:45:52: [2051214 - 00_master] ActionIndex: proton-action-v1-000012 | First: 117308394 | Last: 120000000

2022-04-02T16:45:54: [2051214 - 00_master] DeltaIndex: proton-delta-v1-000008 | First: 70000001 | Last: 80000000

2022-04-02T16:45:54: [2051214 - 00_master] DeltaIndex: proton-delta-v1-000009 | First: 80000001 | Last: 80635816

2022-04-02T16:45:56: [2051214 - 00_master] DeltaIndex: proton-delta-v1-000006 | First: 50000001 | Last: 60000000

2022-04-02T16:45:59: [2051214 - 00_master] DeltaIndex: proton-delta-v1-000007 | First: 60000001 | Last: 70000000

2022-04-02T16:45:59: [2051214 - 00_master] DeltaIndex: proton-delta-v1-000004 | First: 30000001 | Last: 40000000

2022-04-02T16:46:01: [2051214 - 00_master] DeltaIndex: proton-delta-v1-000005 | First: 40000001 | Last: 50000000

2022-04-02T16:46:03: [2051214 - 00_master] DeltaIndex: proton-delta-v1-000002 | First: 10000001 | Last: 20000000

2022-04-02T16:46:05: [2051214 - 00_master] DeltaIndex: proton-delta-v1-000003 | First: 20000001 | Last: 30000000

2022-04-02T16:46:07: [2051214 - 00_master] DeltaIndex: proton-delta-v1-000001 | First: 9 | Last: 10000000

2022-04-02T16:46:07: [2051214 - 00_master] DeltaIndex: proton-delta-v1-000013 | First: 120000001 | Last: 121070391

2022-04-02T16:46:07: [2051214 - 00_master] DeltaIndex: proton-delta-v1-000011 | First: 100000001 | Last: 100005113

2022-04-02T16:46:08: [2051214 - 00_master] DeltaIndex: proton-delta-v1-000012 | First: 117308394 | Last: 120000000

2022-04-02T16:46:08: [2051214 - 00_master] DeltaIndex: proton-delta-v1-000010 | First: 100000000 | Last: 100000000

2022-04-02T16:46:08: [2051214 - 00_master] Indexer rewrite enabled (0 - 1000)

2022-04-02T16:46:08: [2051214 - 00_master] Delta streaming enabled!

2022-04-02T16:46:08: [2051214 - 00_master] Action trace streaming enabled!

Traceback (most recent call last):
  File "scripts/fix_missing_blocks/fix-missing-blocks.py", line 284, in <module>
    MagicFuzz(gt_lt_list)
  File "scripts/fix_missing_blocks/fix-missing-blocks.py", line 188, in MagicFuzz
    startRewrite(gt,lt)
  File "scripts/fix_missing_blocks/fix-missing-blocks.py", line 213, in startRewrite
    print(line)
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 43-44: ordinal not in range(256)
```

**Comment by igorls** [comment]
please reopen if relevant on the latest version and include more information on the issue
