### ISSUE TITLE
Indexer error - RangeError: Invalid typed array

### ISSUE THREAD

**Issue by bensig** [eosrio/hyperion-history-api#97]
Nodeos: `2.1`
Parser: `2.1`

Could be another issue with the indexer due to addons/eosjs-native not being updated. Hopefully this is helpful. It causes my indexer to stop indexing the entire range when this occurs. I was unable to tell which exact tx is causing this. Happy to provide access to my ship node if you want to debug.

Proton block: [57940010](https://www.protonscan.io/block/57940010)

```
2022-04-03T20:11:47: RangeError: Invalid typed array length: 49326109116587355612366462438421e2944484
2022-04-03T20:11:47:     at new Uint8Array (<anonymous>)
2022-04-03T20:11:47:     at keyToString (/opt/eosio/src/Hyperion-History-API/addons/src/eosjs-numeric.ts:302:2)
2022-04-03T20:11:47:     at Object.signatureToString (/opt/eosio/src/Hyperion-History-API/addons/eosjs-native/eosjs-numeric.js:460:16)
2022-04-03T20:11:47:     at SerialBuffer.getSignature (/opt/eosio/src/Hyperion-History-API/addons/src/eosjs-serialize.ts:521:24)
2022-04-03T20:11:47:     at Object.deserialize (/opt/eosio/src/Hyperion-History-API/addons/src/eosjs-serialize.ts:952:63)
2022-04-03T20:11:47:     at Object.deserializeArray [as deserialize] (/opt/eosio/src/Hyperion-History-API/addons/src/eosjs-serialize.ts:701:34)
2022-04-03T20:11:47:     at Object.deserializeStruct [as deserialize] (/opt/eosio/src/Hyperion-History-API/addons/src/eosjs-serialize.ts:661:45)
2022-04-03T20:11:47:     at Object.deserializeVariant [as deserialize] (/opt/eosio/src/Hyperion-History-API/addons/src/eosjs-serialize.ts:686:36)
2022-04-03T20:11:47:     at Object.deserializeStruct [as deserialize] (/opt/eosio/src/Hyperion-History-API/addons/src/eosjs-serialize.ts:661:45)
2022-04-03T20:11:47:     at Object.deserializeStruct [as deserialize] (/opt/eosio/src/Hyperion-History-API/addons/src/eosjs-serialize.ts:661:45)
2022-04-03T20:11:47:     at Object.deserializeVariant [as deserialize] (/opt/eosio/src/Hyperion-History-API/addons/src/eosjs-serialize.ts:686:36)
2022-04-03T20:11:47:     at Object.deserializeStruct [as deserialize] (/opt/eosio/src/Hyperion-History-API/addons/src/eosjs-serialize.ts:661:45)
2022-04-03T20:11:47:     at Object.deserializeArray [as deserialize] (/opt/eosio/src/Hyperion-History-API/addons/src/eosjs-serialize.ts:701:34)
2022-04-03T20:11:47:     at Object.deserializeStruct [as deserialize] (/opt/eosio/src/Hyperion-History-API/addons/src/eosjs-serialize.ts:661:45)
2022-04-03T20:11:47:     at Object.deserializeVariant [as deserialize] (/opt/eosio/src/Hyperion-History-API/addons/src/eosjs-serialize.ts:686:36)
2022-04-03T20:11:47:     at Object.deserializeOptional [as deserialize] (/opt/eosio/src/Hyperion-History-API/addons/src/eosjs-serialize.ts:718:32)
```

**Comment by igorls** [comment]
Closing — this issue references a version of Hyperion that has been superseded by v4.x. If you still experience this on the latest version, please open a new issue.
